### PR TITLE
Try to Fix #12

### LINKED ISSUE #12: Cannot start the program with F5
Hi, 
I just installed vscode insiders for windows and cloned the repo. When opening it as hitting F5 here's what I am getting

```
src/extension.ts:67:7 - error TS2345: Argument of type '{ text: string; range: vscode.Range; trackingId: string; }' is not assignable to parameter of type 'CustomInlineCompletionItem'.
  Object literal may only specify known properties, and 'text' does not exist in type 'CustomInlineCompletionItem'.

67       text: rs.completions[i],
         ~~~~~~~~~~~~~~~~~~~~~~~

[10:25:11] Found 1 error. Watching for file changes.
```

Not knowing nodejs, i have no clue where to start

### PR DESCRIPTION
**Pull request by MHuiG**
Try to Fix #12

I found that there is no error by deleting these lines, I don't know what is the use of these lines, and whether there will be any side effects

It works fine on VSC 1.68.1

image

版本: 1.68.1 (user setup)
提交: 30d9c6cd9483b2cc586687151bcbcd635f373630
日期: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.17134

### CODE REVIEW

**Comment by MHuiG** [comment]
I took a look, the configuration menu is gone, it should be deleted
